## -----------------------------------------------
## Basic Configuration
## -----------------------------------------------

relativeURLs = "true"
baseURL = "/"

title = "Hugo Story"
theme = "hugo-story"


## -----------------------------------------------
## Hugo Built-in Features
## -----------------------------------------------

disableKinds = ["taxonomy", "taxonomyTerm", "section"]
# googleAnalytics = "your-google-analytics-id"


## -----------------------------------------------
## Site Parameters
## -----------------------------------------------

[Params]
  description = "A (modular, highly tweakable) responsive one-page theme for Hugo"
  logo = "images/matsdohla.jpg"
  favicon = true

[Params.social]
  instagram = "https://instagram.com/wingotours"
  facebook = "https://facebook.com/WinGoTours"
  email = "info@wingo.tours"
  tripadvisor = "https://www.tripadvisor.com/Attraction_Review-g294195-d14135104-Reviews-Wingo_Tours-Tbilisi.html"
  whatsapp = "https://api.whatsapp.com/send/?phone=995599920311"